from selenium import webdriver
from selenium.webdriver.support.ui import Select
import time
import random
import string

random_login = "easy_login"#''.join(random.choice(string.ascii_letters) for i in range(10))
def testRegisterUserPage():
    driver = webdriver.Firefox(executable_path="./geckodriver.exe")
    driver.get("http://localhost:3000/login")
    time.sleep(2)
    elem = driver.find_element_by_id(id_="sign-up-container")
    elem.click()
    time.sleep(2)
    elem = driver.find_element_by_id(id_="register-login")
    elem.send_keys(random_login)
    time.sleep(2)
    elem = driver.find_element_by_id(id_="register-password")
    elem.send_keys("newPassword")
    time.sleep(1)
    elem = driver.find_element_by_id(id_="register-button-confirm")
    elem.click()
    time.sleep(5)
    driver.quit()

def testLoginUserPage():
    driver = webdriver.Firefox(executable_path="./geckodriver.exe")
    driver.get("http://localhost:3000/login")
    time.sleep(2)
    elem = driver.find_element_by_id(id_="login-login")
    elem.send_keys(random_login)
    time.sleep(2)
    elem = driver.find_element_by_id(id_="login-password")
    elem.send_keys("newPassword")
    time.sleep(2)
    elem = driver.find_element_by_id(id_="login-button-confirm")
    elem.click()
    time.sleep(5)
    driver.quit()

def testLogoutUserPage():
    driver = webdriver.Firefox(executable_path="./geckodriver.exe")
    driver.get("http://localhost:3000/login")
    elem = driver.find_element_by_id(id_="login-login")
    elem.send_keys(random_login)
    elem = driver.find_element_by_id(id_="login-password")
    elem.send_keys("newPassword")
    elem = driver.find_element_by_id(id_="login-button-confirm")
    elem.click()
    time.sleep(2)
    elem = driver.find_element_by_id(id_="logout-button-confirm")
    elem.click()
    time.sleep(5)
    driver.quit()

def testViewStationListUser():
    driver = webdriver.Firefox(executable_path="./geckodriver.exe")
    driver.get("http://localhost:3000/login")
    elem = driver.find_element_by_id(id_="login-login")
    elem.send_keys(random_login)
    elem = driver.find_element_by_id(id_="login-password")
    elem.send_keys("newPassword")
    elem = driver.find_element_by_id(id_="login-button-confirm")
    elem.click()
    elem = driver.find_element_by_id(id_="topbar-station-button-confirm")
    elem.click()
    time.sleep(5)
    driver.quit()

def testViewBikeListUser():
    driver = webdriver.Firefox(executable_path="./geckodriver.exe")
    driver.get("http://localhost:3000/login")
    elem = driver.find_element_by_id(id_="login-login")
    elem.send_keys(random_login)
    elem = driver.find_element_by_id(id_="login-password")
    elem.send_keys("newPassword")
    elem = driver.find_element_by_id(id_="login-button-confirm")
    elem.click()
    elem = driver.find_element_by_id(id_="topbar-station-button-confirm")
    elem.click()
    time.sleep(2)
    elem = driver.find_element_by_id(id_="station-button-confirm-0")
    elem.click()
    time.sleep(5)
    driver.quit()

def testRentBiketUser():
    driver = webdriver.Firefox(executable_path="./geckodriver.exe")
    driver.get("http://localhost:3000/login")
    elem = driver.find_element_by_id(id_="login-login")
    elem.send_keys(random_login)
    elem = driver.find_element_by_id(id_="login-password")
    elem.send_keys("newPassword")
    elem = driver.find_element_by_id(id_="login-button-confirm")
    elem.click()
    elem = driver.find_element_by_id(id_="topbar-station-button-confirm")
    elem.click()
    elem = driver.find_element_by_id(id_="station-button-confirm-2")
    elem.click()
    time.sleep(1)
    elem = driver.find_element_by_id(id_="bike-rent-button-confirm-0")
    elem.click()
    time.sleep(1)
    elem = driver.find_element_by_id(id_="bike-rent-button-confirm")
    elem.click()
    time.sleep(5)
    driver.quit()

def testReturnBiketUser():
    driver = webdriver.Firefox(executable_path="./geckodriver.exe")
    driver.get("http://localhost:3000/login")
    elem = driver.find_element_by_id(id_="login-login")
    elem.send_keys(random_login)
    elem = driver.find_element_by_id(id_="login-password")
    elem.send_keys("newPassword")
    elem = driver.find_element_by_id(id_="login-button-confirm")
    elem.click()
    elem = driver.find_element_by_id(id_="topbar-station-button-confirm")
    elem.click()
    elem = driver.find_element_by_id(id_="station-button-confirm-2")
    elem.click()
    elem = driver.find_element_by_id(id_="bike-rent-button-confirm-0")
    elem.click()
    elem = driver.find_element_by_id(id_="bike-rent-button-confirm")
    elem.click()
    time.sleep(1)
    elem = driver.find_element_by_id(id_="topbar-rented-button-confirm")
    elem.click()
    time.sleep(1)
    elem = driver.find_element_by_id(id_="return-bike-button-0")
    elem.click()
    time.sleep(1)
    stationListSelect =  Select(driver.find_element_by_id(id_="select-return-bike-station"))
    stationListSelect.select_by_visible_text("Uniwersytet")
    time.sleep(1)
    elem = driver.find_element_by_id(id_="dialog-return-bike-button-confirm")
    elem.click()
    time.sleep(5)
    driver.quit()              

def testAll():
    if random_login != "easy_login":
        testRegisterUserPage()
    #testLoginUserPage()
    #testLogoutUserPage()
    #testViewStationListUser()
    #testViewBikeListUser()
    #testRentBiketUser()
    testReturnBiketUser()

testAll()